import type { Metadata } from "next";
import { FoldersProvider } from "@/components/FoldersProvider";
import { BookmarksProvider } from "@/components/BookmarksProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <FoldersProvider>
          <BookmarksProvider>{children}</BookmarksProvider>
        </FoldersProvider>
      </body>
    </html>
  );
}
